export {
  CopyTradeApiError,
  copyTradeRequest,
  getCopyTradeApiBaseUrl,
} from "./client";

export {
  createCopyTradeDepositAddress,
  createCopyTradeUser,
  createCopyTradeWallet,
  createCopyTradeWithdrawal,
  getCopyTradeBalances,
  getCopyTradeDepositStatus,
  getCopyTradeDepositSupportedAssets,
  getCopyTradePlatformMetrics,
  getCopyTradePnL,
  getCopyTradePnLPoints,
  getCopyTradeProfile,
  getCopyTradeSellableBalance,
  getCopyTradeTargets,
  getCopyTradeWallet,
  getCopyTradeWithdrawalReadiness,
  getCopyTradeWithdrawalSupportedAssets,
  listCopyTradeOrders,
  listCopyTradeWithdrawals,
  listCopyTraders,
  sellCopyTradePosition,
  updateCopyTradeProfile,
  updateCopyTradeTargets,
} from "./endpoints";
